#Database configuration MySql
driver : mysql
#host : baseamaz.covejhmqeh6p.us-west-2.rds.amazonaws.com
port : 3306
#database : baseAmazBase
#user : jarKanNos
#password : jgjk89JKLKKS89hjKJ
charset : utf8
host : localhost
user : izi
database : izi
password : kuzOL985fkpLdiI6
